[Obs AI Assistant] Retry API cleanup (#220885)
Retry the `deleteByQuery` operation in `clearKnowledgeBase` to prevent
intermittent failures like this:
```

search_phase_execution_exception: Search rejected due to missing shards [[.kibana-observability-ai-assistant-kb-000002][0]]. Consider using `allow_partial_search_results` setting to bypass this error.

at SniffingTransport._request (node_modules/@elastic/elasticsearch/node_modules/@elastic/transport/src/Transport.ts:591:17)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at /root/.qaf/data/git/kibana/node_modules/@elastic/elasticsearch/node_modules/@elastic/transport/src/Transport.ts:697:22
at SniffingTransport.request (node_modules/@elastic/elasticsearch/node_modules/@elastic/transport/src/Transport.ts:694:14)
at Client.DeleteByQueryApi [as deleteByQuery] (node_modules/@elastic/src/api/api/delete_by_query.ts:129:10)
at Context. (knowledge_base_basic_operations.spec.ts:156:9)
at Object.apply (wrap_function.js:74:16)
```