[Workplace AI] Fix i18n issues with angle-bracketed text in Slack defaultMessage (#254517)
## Summary

This PR fixes some i18n formatting issues in Slack Data Source's
`defaultMessage` fields, and adds some consistency between the Workflow
YAMLs and those `defaultMessage` fields.

## The Issue
The following error message was appearing in Kibana logs, presumably
when translation was happening:

```
Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting default message for: "core.kibanaConnectorSpecs.slack.actions.searchMessages.input.before.description", rendering default message verbatim
MessageID: core.kibanaConnectorSpecs.slack.actions.searchMessages.input.before.description
Default Message: Optional Slack search constraint. Adds `before:<date>` to the query (e.g. 2026-02-10).
Description: undefined

Locale: en

UNCLOSED_TAG
SyntaxError: UNCLOSED_TAG (at error.js:58:1)
    at IntlMessageFormat.parse [as __parse] (index.js:31:1)
    at new IntlMessageFormat (core.js:137:1)
    at utils.js:110:1
    at variadic (index.js:33:1)
    at formatMessage (message.js:69:1)
```

## The Solution
In `slack.ts`, we previously had text like `in:<date>` and
`in:<channel_id>`. i18n's FormatJS treats these are rich-text tags, and
expects a closing tag (ie `</data> or </channel_id>`), which, of course,
is not the intent.

Angle bracket usage has now been removed everywhere.

## Impact
There should be no tangible impact to the expected output or LLM usage
of the tools and Workflows.

### Checklist

Check the PR satisfies following conditions. 

Reviewers should verify this PR satisfies this list as well.

- [x] Any text added follows [EUI's writing
guidelines](https://elastic.github.io/eui/#/guidelines/writing), uses
sentence case text and includes [i18n
support](https://github.com/elastic/kibana/blob/main/src/platform/packages/shared/kbn-i18n/README.md)
- [x] The PR description includes the appropriate Release Notes section,
and the correct `release_note:*` label is applied per the
[guidelines](https://www.elastic.co/guide/en/kibana/master/contributing.html#kibana-release-notes-process)
- [x] Review the [backport
guidelines](https://docs.google.com/document/d/1VyN5k91e5OVumlc0Gb9RPa3h1ewuPE705nRtioPiTvY/edit?usp=sharing)
and apply applicable `backport:*` labels.